config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :projects

  map.login    '/login', :controller => 'sessions', :action => 'new'
  map.logout    '/logout', :controller => 'sessions', :action => 'destroy'
  map.resource  :session
  
  map.resources :entries
  map.resources :feeds
  map.resources :users, :as => 'members'

  

  map.root :controller => "welcome"
  
  map.user_slug '/:id', :controller => 'users', :action => 'show'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Twittable
  
  has_and_belongs_to_many :users
  
  validates_presence_of :name, :url
  validates_format_of :url, :with => REXP_URL
  validates_uniqueness_of :url
  
  # Use project's name as its title
  def title
    name
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :admin_required, :except => [:index, :show]  
  
  # GET /projects
  def index
    @projects = Project.all(:order => :name)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /projects/1
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /projects/new
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url, :notice => 'Project was successfully removed.') }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_list.html.erb
<div class="span-7 colborder">
  <h2>projects</h2>
</div>
<div class="span-15 last">
	<% @projects.each do |p| %>
		<%= render :partial => 'projects/project', :locals => {:project => p} %>
	<% end %>
</div>
<hr class="space" />
<hr/>

app/views/projects/_project.html.erb
<div class="span-12 last">
	<h3><strong><%= project.name %></strong> <small>by <%= project.users.map {|u| "#{link_to(u.name, user_slug_path(u))}"}.join(", ").html_safe %></small></h3>
	<p><%= link_to project.url.gsub("http://", ""), project.url %></p>
	<blockquote><%= simple_format(project.description) %></blockquote>
	
	<% if admin? %>
  	<p>
			<%= link_to 'Edit', edit_project_path(project) %> | 
  		<%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %>
		</p>
	<% end %>
</div>

app/views/projects/edit.html.erb
<div class="span-7">
  <h2>Projects</h2>
</div>

<div class="span-15 leftborder last">
	<h3>Editing project</h3>

	<% form_for(@project) do |f| %>
	  <%= f.error_messages %>

	  <p>
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </p>
	  <p>
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	  </p>
	  <p>
	    <%= f.label :url %><br />
	    <%= f.text_field :url %>
	  </p>
		<p>
			<label>People involved in this project</label><br />
			<% User.find(:all, :order => 'name').each do |u| %>
				<%= check_box_tag("project[user_ids][]", u.id, @project.users.include?(u)) %>
			 	<%= u.name %><br />
			<% end %>
		</p>
	  <p>
	    <%= f.submit 'Update' %>
	  </p>
	<% end %>

	<%= link_to 'Show', @project %> |
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="span-7">
  <h2>Projects</h2>
</div>

<div class="span-15 leftborder last">
	<% @projects.each do |project| %>
		<%= render :partial => 'projects/project', :locals => { :project => project } %>
		<% if project != @projects.last %>
			<hr />
		<% end %>
	<% end %>

	<% if admin? %>
		<br class="clear" />
		<p>
			<%= link_to 'New project', new_project_path %>
		</p>
	<% end %>
</div>

app/views/projects/new.html.erb
<div class="span-7">
  <h2>Projects</h2>
</div>

<div class="span-15 leftborder last">
	<h3>New project</h3>

	<% form_for(@project) do |f| %>
	  <%= f.error_messages %>

	  <p>
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </p>
	  <p>
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	  </p>
	  <p>
	    <%= f.label :url %><br />
	    <%= f.text_field :url %>
	  </p>
		<p>
			<label>People involved in this project</label><br />
			<% User.find(:all, :order => 'name').each do |u| %>
				<%= check_box_tag("project[user_ids][]", u.id, @project.users.include?(u)) %>
			 	<%= u.name %><br />
			<% end %>
		</p>
	  <p>
	    <%= f.submit 'Create' %>
	  </p>
	<% end %>
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="span-7">
  <h2>Projects</h2>
</div>

<div class="span-15 leftborder last">
	<%= render :partial => 'projects/project', :locals => { :project => @project }  %>
</div>